### ISSUE TITLE
2. Adding a CSS Framework

### ISSUE THREAD

**Issue by teknofage** [MakeSchool-Tutorials/Launch-Page-Tutorial#1]
Having screenshots every few steps so that we know that what we are creating is aligning with the tutorial would be helpful. I can't tell whether  I am going off track unless I check someone else's code.

**Comment by ibirnam** [comment]
Good suggestion @teknofage! I added some screenshots in cd9551d3fbb69e2a968d1e515efc103f35b85fcf , should be live later today!
