### ISSUE TITLE
4. Images and Videos

### ISSUE THREAD

**Issue by Rasenku** [MakeSchool-Tutorials/Launch-Page-Tutorial#2]
I would like to add feedback that is when adding youtube videos you should also add that you must replace "watch" with "embed" when copying the link from a youtube video and do a / with the video id for it to work and for it to not say "playback error".

**Comment by ibirnam** [comment]
Thanks @Rasenku! I've addressed this in 586b05bf0907f772b6601a9bae02de81b3fa344e, will go live today!
